/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FrikandevHeading {
        "size": number;
    }
}
declare global {
    interface HTMLFrikandevHeadingElement extends Components.FrikandevHeading, HTMLStencilElement {
    }
    var HTMLFrikandevHeadingElement: {
        prototype: HTMLFrikandevHeadingElement;
        new (): HTMLFrikandevHeadingElement;
    };
    interface HTMLElementTagNameMap {
        "frikandev-heading": HTMLFrikandevHeadingElement;
    }
}
declare namespace LocalJSX {
    interface FrikandevHeading {
        "size"?: number;
    }
    interface IntrinsicElements {
        "frikandev-heading": FrikandevHeading;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "frikandev-heading": LocalJSX.FrikandevHeading & JSXBase.HTMLAttributes<HTMLFrikandevHeadingElement>;
        }
    }
}
